#!/bin/bash
# Generated by dsh-super-injector dev_scaffold_plugin.
# Build: compile src/ to lib/. Two modes auto-selected:
#   1) DSH_CHECKOUT mode (source checkout): link official packages + checkout tsc;
#   2) npm-installed dsh mode: link official packages from the global dsh
#      installation + npx-public typescript. No registry official deps needed.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

CHECKOUT="${DSH_CHECKOUT:-}"
if [ -z "$CHECKOUT" ]; then
  for candidate in "$HOME/dsh-harness" "$HOME/dsh" "$HOME/.dsh/dsh-harness"; do
    if [ -d "$candidate/packages" ]; then CHECKOUT="$candidate"; break; fi
  done
fi
HAVE_CHECKOUT=0
if [ -n "$CHECKOUT" ] && [ -d "$CHECKOUT/packages" ] && { [ -x "$CHECKOUT/node_modules/.bin/tsc" ] || [ -f "$CHECKOUT/node_modules/.bin/tsc.cmd" ]; }; then
  HAVE_CHECKOUT=1
fi

# 通用 junction 工具（link 路径 → target 绝对路径）
mk_link() {
  node -e "
    const fs = require('fs');
    const path = require('path');
    const link = path.resolve(process.argv[1]);
    const target = path.resolve(process.argv[2]);
    fs.rmSync(link, { recursive: true, force: true });
    fs.mkdirSync(path.dirname(link), { recursive: true });
    fs.symlinkSync(target, link, process.platform === 'win32' ? 'junction' : 'dir');
  " "$1" "$2"
}

if [ "$HAVE_CHECKOUT" = 1 ]; then
  TSC="$CHECKOUT/node_modules/.bin/tsc"
  echo "=== Linking build dependencies (checkout: $CHECKOUT) ==="
  mkdir -p node_modules/@deepseek-ai
  node -e "const fs=require('fs');fs.rmSync('node_modules/@standard-schema',{recursive:true,force:true})"
  mk_link node_modules/cordis "$CHECKOUT/vendor/cordis"
  mk_link node_modules/cosmokit "$CHECKOUT/vendor/cosmokit"
  mk_link node_modules/schemastery "$CHECKOUT/vendor/schemastery"
  mk_link node_modules/@deepseek-ai/dsh-tools "$CHECKOUT/packages/core/tools"
  mk_link node_modules/@deepseek-ai/dsh-llm "$CHECKOUT/packages/llm/llm"
  mk_link node_modules/@deepseek-ai/dsh-system-prompt "$CHECKOUT/packages/core/system-prompt"
  mk_link node_modules/@types/node "$CHECKOUT/node_modules/@types/node"
  STD_SCHEMA=$(find "$CHECKOUT/node_modules/.pnpm" -maxdepth 1 -type d -iname '@standard-schema+spec@*' 2>/dev/null | head -1)
  if [ -n "$STD_SCHEMA" ]; then
    node -e "
      const fs = require('fs');
      const path = require('path');
      fs.rmSync('node_modules/@standard-schema', { recursive: true, force: true });
      fs.mkdirSync('node_modules/@standard-schema', { recursive: true });
      fs.symlinkSync(path.resolve(process.argv[1]), path.resolve('node_modules/@standard-schema/spec'), process.platform === 'win32' ? 'junction' : 'dir');
    " "$STD_SCHEMA/node_modules/@standard-schema/spec"
  fi
  echo "=== Compiling src to lib (checkout) ==="
  "$TSC" -p tsconfig.json
else
  echo "=== Self-contained build (npm-installed dsh mode) ==="
  NPM_ROOT="${DSH_NPM_ROOT:-}"
  if [ -z "$NPM_ROOT" ] && command -v npm >/dev/null 2>&1; then
    NPM_ROOT="$(npm root -g 2>/dev/null)/@deepseek-ai/dsh"
  fi
  if [ ! -d "$NPM_ROOT/node_modules" ]; then
    echo "build: no source checkout and no npm-installed dsh at $NPM_ROOT" >&2
    echo "       set DSH_CHECKOUT to a source checkout, or install dsh globally (npm i -g @deepseek-ai/dsh)" >&2
    exit 1
  fi
  echo "=== Linking official packages (npm root: $NPM_ROOT) ==="
  mkdir -p node_modules/@deepseek-ai node_modules/@types
  for pkg in "$NPM_ROOT"/node_modules/@deepseek-ai/*; do
    name="$(basename "$pkg")"
    [ -e "node_modules/@deepseek-ai/$name" ] || mk_link "node_modules/@deepseek-ai/$name" "$pkg"
  done
  mk_link node_modules/cordis "$NPM_ROOT/node_modules/@deepseek-ai/cordis"
  mk_link node_modules/schemastery "$NPM_ROOT/node_modules/@deepseek-ai/schemastery"
  mk_link node_modules/@types/node "$NPM_ROOT/node_modules/@types/node"
  [ -e node_modules/@standard-schema ] || mk_link node_modules/@standard-schema "$NPM_ROOT/node_modules/@standard-schema"
  echo "=== Compiling src to lib (self-contained) ==="
  if [ -x node_modules/.bin/tsc ]; then
    node_modules/.bin/tsc -p tsconfig.json
  elif command -v npx >/dev/null 2>&1; then
    npx --yes -p typescript@^5.9.2 tsc -p tsconfig.json
  else
    echo "build: no local tsc and no npx available; run pnpm install first or install typescript" >&2
    exit 1
  fi
fi
echo "=== Build complete ==="
